org: nibras39
app: flowerey-adaptor
service: flowerey-adaptor

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handlers/graphql/index.graphqlHandler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /
          method: post
          cors: true          

plugins:
  - serverless-offline
