org: nibras39
app: flowerey-adaptor
service: flowerey-adaptor

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: GET

plugins:
  - serverless-offline          
  - apollo-server-lambda-graphql